#!/bin/bash

mvn_log="$(mvn dependency:copy-dependencies)"
if [[ $? != 0 ]]; then
  echo "${mvn_log}" >&2
  exit 1
fi

java -cp "target/dependency/*:target/classes"  com.neo4j.tools.dump.DumpLogicalLog $*
